name: release


on:
 #release: 
 #  types: ["published"]
 push: 
    tags: 
      - v*

permissions: 
  packages: write
  contents: write

jobs:
  relase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: goreleaser/goreleaser-action@v6
        with:
         args: release --clean
        env:
          GITHUB_TOKEN: ${{ github.token }}