name: release


on:
 #release: 
 #  types: ["published"]
 push: 
    tags: 
      - v*

permissions: 
  packages: write
  contents: write

jobs:
  relase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
            go-version-file: 'go.mod'
      - uses: goreleaser/goreleaser-action@v6
        with:
         args: release --clean
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: create PR in krew index
        run: |
            export TAG=$(echo "${{ github.ref }}" | sed -e 's/refs\/tags\///')
            echo "creating PR in krew index for release $TAG"
            wget https://github.com/zak905/kubectl-resource-backup/releases/download/$TAG/checksums.txt

            cat checksums.txt | \
            awk '{sub(/kubectl-resource-backup_/, "", $2); sub(/\.tar\.gz/, "", $2); printf "%s_SHA256=%s\n", toupper($2), $1}' > values.env

            cat values.env

            set -a
            source values.env
            set +a

            cat .krew.yaml.tpl | envsubst > resource-backup.yaml

            git config --global user.name "zak905"
            git config --global user.email "${{ secrets.GH_EMAIL }}"


            #update krew index fork
            git clone https://github.com/zak905/krew-index.git
            cp resource-backup.yaml krew-index/plugins/
            cd krew-index
            git remote set-url origin https://zak905:${{ secrets.GH_TOKEN }}@github.com/zak905/krew-index.git
            export BRANCH_NAME=resource_backup_version_$TAG
            git checkout -b $BRANCH_NAME
            git add plugins
            git commit -m "resouce-backup: upgrade to version $TAG"
            git push origin $BRANCH_NAME

            #create pull request
            PR_URL=$(curl -v -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/kubernetes-sigs/krew-index/pulls \
            -d "{\"title\":\"resource-backup: upgrade to version $TAG\",\"body\":\"This is an automated PR created from a github action.\",\"head\":\"zak905:$BRANCH_NAME\",\"base\":\"master\"}" \
            | jq .html_url)

            #output PR URL to action to summary
            echo "PR: [$PR_UR]($PR_URL)" >> $GITHUB_STEP_SUMMARY

